### ISSUE TITLE
Kiwi generator crash boolean expression must not be null

### ISSUE THREAD

**Issue by vanlooverenkoen** [vanlooverenkoen/kiwi#49]
```
Failed assertion: boolean expression must not be null
#0      ElementDisplayStringBuilder._writeNullability (package:analyzer/src/dart/element/display_string_builder.dart:252:9)
#1      ElementDisplayStringBuilder.writeInterfaceType (package:analyzer/src/dart/element/display_string_builder.dart:152:5)
#2      InterfaceTypeImpl.appendTo (package:analyzer/src/dart/element/type.dart:840:13)
#3      TypeImpl.getDisplayString (package:analyzer/src/dart/element/type.dart:1696:5)
#4      KiwiInjectorGenerator._generateRegister (package:kiwi_generator/src/kiwi_injector_generator.dart:135:43)
#5      KiwiInjectorGenerator._generateRegisters.<anonymous closure> (package:kiwi_generator/src/kiwi_injector_generator.dart:122:13)
#6      MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#7      new List.from (dart:core-patch/array_patch.dart:50:19)
#8      new List.of (dart:core-patch/array_patch.dart:68:17)
#9      Iterable.toList (dart:core/iterable.dart:404:12)
#10     KiwiInjectorGenerator._generateRegisters (package:kiwi_generator/src/kiwi_injector_generator.dart:123:10)
#11     KiwiInjectorGenerator._generateInjectorMethod.<anonymous closure>.<anonymous closure> (package:kiwi_generator/src/kiwi_injector_generator.dart:114:31)
#12     _$BlockBuilder.update (package:code_builder/src/specs/code.g.dart:82:33)
#13     new _$Block (package:code_builder/src/specs/code.g.dart:14:28)
#14     KiwiInjectorGenerator._generateInjectorMethod.<anonymous closure> (package:kiwi_generator/src/kiwi_injector_generator.dart:111:18)
#15     new Method.returnsVoid.<anonymous closure> (package:code_builder/src/specs/method.dart:31:18)
#16     _$MethodBuilder.update (package:code_builder/src/specs/method.g.dart:345:33)
#17     new _$Method (package:code_builder/src/specs/method.g.dart:38:29)
#18     new Method.returnsVoid (package:code_builder/src/specs/method.dart:29:7)
#19     KiwiInjectorGenerator._generateInjectorMethod (package:kiwi_generator/src/kiwi_injector_generator.dart:84:19)
#20     KiwiInjectorGenerator._generateInjectorMethods.<anonymous closure> (package:kiwi_generator/src/kiwi_injector_generator.dart:69:21)
#21     MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#22     new List.from (dart:core-patch/array_patch.dart:50:19)
#23     new List.of (dart:core-patch/array_patch.dart:68:17)
#24     Iterable.toList (dart:core/iterable.dart:404:12)
#25     KiwiInjectorGenerator._generateInjectorMethods (package:kiwi_generator/src/kiwi_injector_generator.dart:70:10)
#26     KiwiInjectorGenerator._generateInjector.<anonymous closure> (package:kiwi_generator/src/kiwi_injector_generator.dart:63:24)
#27     _$ClassBuilder.update (package:code_builder/src/specs/class.g.dart:312:33)
#28     new _$Class (package:code_builder/src/specs/class.g.dart:34:28)
#29     KiwiInjectorGenerator._generateInjector (package:kiwi_generator/src/kiwi_injector_generator.dart:60:12)
#30     KiwiInjectorGenerator.generate.<anonymous closure>.<anonymous closure> (package:kiwi_generator/src/kiwi_injector_generator.dart:43:34)
#31     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#32     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#33     List.addAll (dart:core-patch/growable_array.dart:226:13)
#34     ListBuilder.addAll (package:built_collection/src/list/list_builder.dart:106:14)
#35     KiwiInjectorGenerator.generate.<anonymous closure> (package:kiwi_generator/src/kiwi_injector_generator.dart:42:16)
#36     _$LibraryBuilder.update (package:code_builder/src/specs/library.g.dart:104:33)
#37     new _$Library (package:code_builder/src/specs/library.g.dart:16:30)
#38     KiwiInjectorGenerator.generate (package:kiwi_generator/src/kiwi_injector_generator.dart:41:20)
#39     _generate (package:source_gen/src/builder.dart:303:33)
<asynchronous suspension>
#40     _Builder._generateForLibrary (package:source_gen/src/builder.dart:79:15)
#41     _Builder.build (package:source_gen/src/builder.dart:71:11)
<asynchronous suspension>
#42     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#43     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#44     ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#45     Future.wait (dart:async/future.dart:406:26)
#46     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#47     _rootRun (dart:async/zone.dart:1190:13)
#48     _CustomZone.run (dart:async/zone.dart:1093:19)
#49     _runZoned (dart:async/zone.dart:1630:10)
#50     runZonedGuarded (dart:async/zone.dart:1618:12)
#51     runZoned (dart:async/zone.dart:1547:12)
#52     scopeLogAsync (package:build/src/builder/logging.dart:26:3)
#53     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#54     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:485:19)
#55     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#56     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:483:23)
<asynchronous suspension>
#57     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#58     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#59     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:440:22)
#60     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#61     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:436:17)
#62     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)
#63     MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#64     Future.wait (dart:async/future.dart:406:26)
#65     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)
#66     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
#67     _rootRunUnary (dart:async/zone.dart:1198:47)
#68     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#69     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#70     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#71     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#72     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#73     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#74     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#75     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#76     _rootRunUnary (dart:async/zone.dart:1198:47)
#77     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#78     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#79     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#80     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#81     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#82     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
#83     _rootRunUnary (dart:async/zone.dart:1198:47)
#84     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#85     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#86     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#87     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#88     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#89     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#90     _rootRun (dart:async/zone.dart:1190:13)
#91     _CustomZone.run (dart:async/zone.dart:1093:19)
#92     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#93     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#94     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#95     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#96     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#97     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)
#98     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by vanlooverenkoen** [comment]
For now we won't support nullability.

**Comment by vanlooverenkoen** [comment]
fixed in:
kiwi: 2.0.1
kiwi_generator: 2.0.1
